### ISSUE TITLE
在Conda的base环境中，CUDA是GPU版本的11.7，Pytorch和torch版本都为1.13.1的情况下，运行gradio_scribble2image.py失败

### ISSUE THREAD

**Issue by znhacker** [lllyasviel/ControlNet#15]
在Pytorch和torch以及CUDA都没有错误的情况下，且在pytorch官网显示一致的情况下，我运行gradio_scribble2image.py一直提示AssertionError:torch not compiled with cuda enabled，然后查询发现，torch.cuda.is_available())始终是False

请求帮助，希望能帮忙指出错误的原因在哪，感恩～！

![fail1](https://user-images.githubusercontent.com/14341380/218301141-50b16f3e-337a-4f2d-8520-bf39eaf618e4.jpg)

![fail2](https://user-images.githubusercontent.com/14341380/218301238-f521b08b-6664-43a7-8cbb-9da01c96de0b.jpg)

![fail3](https://user-images.githubusercontent.com/14341380/218301517-9fce5fd3-020b-4807-8150-16c1aa590e5f.jpg)

![fail4](https://user-images.githubusercontent.com/14341380/218301681-9f722949-a701-480f-b925-1ca230d5f6c1.jpg)

![fail5](https://user-images.githubusercontent.com/14341380/218301680-410dd8a8-e649-4a89-8b23-9386108fde81.jpg)

**Comment by lllyasviel** [comment]
你在用base。先conda activate control

**Comment by znhacker** [comment]
> 你在用base。先conda activate control
好的，非常感谢～！我以为直接在base上就能运行，支持环境全装到base里去了。。。。。我先试试你说的方案～感谢～！

**Comment by FurkanGozukara** [comment]
Wait my video hopefully coming today

**Comment by znhacker** [comment]
> Wait my video hopefully coming today how to install and run https://www.youtube.com/SECourses

Come~on~ it will be cool~!

**Comment by FurkanGozukara** [comment]
> > Wait my video hopefully coming today how to install and run https://www.youtube.com/SECourses
> 
> Come~on~ it will be cool~!

ye here example generation

from this
![image](https://user-images.githubusercontent.com/19240467/218304804-bbaf63c1-2aaa-46e1-b19f-6db32af8c8d4.png)

into this
![image](https://user-images.githubusercontent.com/19240467/218304810-b973829c-9f9f-4c5c-97d5-50d0740811ce.png)

**Comment by znhacker** [comment]
> 你在用base。先conda activate control

搞定了～感谢大佬～这个问题可以关闭了～感恩～！

**Comment by FurkanGozukara** [comment]
@znhacker tutorial released : [Transform Your Sketches into Masterpieces with Stable Diffusion ControlNet AI - How To Use Tutorial](https://www.youtube.com/watch?v=YJebdQ30UZQ)

**Comment by znhacker** [comment]
> @znhacker tutorial released : [Transform Your Sketches into Masterpieces with Stable Diffusion ControlNet AI - How To Use Tutorial](https://www.youtube.com/watch?v=YJebdQ30UZQ)

Bro，it's detailed and cool～
