### ISSUE TITLE
Training on multi GPUs are always OOM while it working well on single GPU

### ISSUE THREAD

**Issue by Zack14159** [lllyasviel/ControlNet#242]
I used 4 Tesla T10 16GB GPU to train my model, but it's wired that it can only run on the mode of gpus=1. My batch_size=4 and I can run it on 1 GPU,  but once I changed my gpus>1 it will be OOM, no matter DDP mode or DP mode to use.  I'm very confused and want to konw that the reason is come from pytorch lightning framework or model construction? 
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/44990856/223613347-f118b14f-06de-441b-845e-a6a6383b1d99.png">
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/44990856/223613461-6ba419e3-e0d3-4acb-aec4-cebd30f6b54a.png">

**Comment by yzy-bupt** [comment]
I have the same problem, and I can't run on muti gpus because the images run on different opus but the prompt runs on the single gpu. Do you have any idea?

**Comment by Zack14159** [comment]
If you want to train it on only single GPU, maybe you can try this:&nbsp;

&nbsp;to ensure your device. But I still don't know how to train it on multi GPUs, can you tell me how you make your images run on different gpus?



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lllyasviel/ControlNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lllyasviel/ControlNet] Training on multi GPUs are always OOM while it working well on single GPU (Issue #242)





 
I have the same problem, and I can't run on muti gpus because the images run on different opus but the prompt runs on the single gpu. Do you have any idea?

**Comment by yzy-bupt** [comment]
You can try setting the strategy='dp', then you can run muti opus, but you may get the same issue as mine.

**Comment by Zack14159** [comment]
I have tried this strategy, but it's stll OOM&nbsp;
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lllyasviel/ControlNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lllyasviel/ControlNet] Training on multi GPUs are always OOM while it working well on single GPU (Issue #242)





 
You can try setting the strategy='dp', then you can run muti opus, but you may get the same issue as mine.

**Comment by SwayStar123** [comment]
try fsdp or deepspeed

**Comment by NorthSummer** [comment]
16 GB is still limited as far as I concern.

**Comment by Zack14159** [comment]
Thanks for everyone, I've resolved the peroblem by using 4 P40 24G. 16GB is not enough for multi GPUs training.
